#!/usr/bin/env python

from subprocess import check_output

command = "bluetoothctl show"

res = check_output(command.split(' ')).decode('utf-8')

trgts = [i for i in res.split('\n') if 'Powered' in i][0]

if 'no' in trgts:
    out = "[off]"

elif 'yes' in trgts:
    out = "[on]"

else:
    out = "Error!"

print(f"🦷 {out}")

