#!/usr/bin/env python

from subprocess import check_output

command = "df /dev/sda2"

res = check_output(command.split(' ')).decode('utf-8')

line = res.split('\n')[1]

line = [i for i in line.split(' ') if i]

tot = int(int(line[1]) / (1024 ** 2))
used = int(int(line[2]) / (1024 ** 2))
avai = int(int(line[3]) / (1024 ** 2))

print(f"💽 Ttl:{tot}GiB Usd:{used}GiB Avai:{avai}GiB ")

